# Generated by Django 4.2.7 on 2023-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('Customer_Reference_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Item_Purchased', models.CharField(max_length=100)),
                ('Purchase_Amount', models.FloatField()),
                ('Review_Rating', models.FloatField()),
                ('Payment_Method', models.CharField(max_length=255)),
            ],
        ),
    ]
